// react-youtube/src/Todo/TodoItem.js
import React, { useContext } from 'react'
import PropTypes from 'prop-types'
import Context from "../context";

const styles = {
  li: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '.5rem 1rem',
    border: '1px solid #ccc',
    borderRadius: '4px',
    marginBottom: '.5rem'
  },
  input: {
    marginRight: '1rem'
  }
};

function TodoItem({todo, index, onChange}) {
  const { removeTodo } = useContext(Context);
  const classes = [];

  if (todo.completed) {
    classes.push('done')
  }

  return <li style={styles.li}>
    <span className={classes.join(' ')}>
      <input type="checkbox"
             checked={todo.completed}
             style={styles.input}
             onChange={
               () => {
                 onChange(todo.id)
               }
             }/>
      <strong>{index + 1}</strong>
      &nbsp;
      {todo.title}
    </span>
    <button className='rm' onClick={removeTodo.bind(null, todo.id)}>
      &times;
    </button>
  </li>
}

TodoItem.propTypes = {
  todo: PropTypes.object.isRequired,
  index: PropTypes.number,
  onChange: PropTypes.func.isRequired
}

export default TodoItem

// vue-crash-course/src/components/TodoItem.vue
<template>
  <div>
    <li>
      <span v-bind:class="{done: todo.completed}">
        <input type="checkbox" v-on:change="todo.completed = !todo.completed">
        <strong>{{ index + 1 }}</strong>
        {{ todo.title }}
      </span>
      <button class="rm" v-on:click="$emit('remove-todo', todo.id)">&times;</button>
    </li>
  </div>
</template>

<script>
  export default {
    props: {
      todo: {
        type: Object,
        required: true
      },
      index: Number
    }
  }
</script>

<style scoped>
  li {
    border: 1px solid #ccc;
    display: flex;
    justify-content: space-between;
    padding: .5rem 2rem;
    margin-bottom: 1rem;
  }

  .rm {
    background: red;
    color: white;
    border-radius: 50%;
    font-weight: bold;
  }

  input {
    margin-right: 1rem;
  }

  .done {
    text-decoration-line: line-through;
  }
</style>
