// vue-crash-course/src/components/TodoList.vue
<template>
  <div>
    <ul>
      <TodoItem
      v-for="todo of todos"
      v-bind:todo="todo"
      />
    </ul>
  </div>
</template>

<script>
  import TodoItem from '@/components/TodoItem'
  export default {
    props: ['todos'],
    components: {
      TodoItem
    }
  }
</script>

<style scoped>
  ul {
    list-style: none;
    margin: 0;
    padding: 0;
  }
</style>

// react-youtube/src/Todo/TodoList.js
import React from 'react'
import PropTypes from 'prop-types'
import TodoItem from "./TodoItem";

const styles = {
  ul: {
    listStyle: 'none',
    margin: 0,
    padding: 0
  }
}

function TodoList(props) {
  return (
    <ul style={styles.ul}>
      {props.todos.map((todo, index) => {
        return <TodoItem todo={todo}
                         key={todo.id}
                         index={index}
                         onChange={props.onToggle}/>
      })}
    </ul>
  )
}

TodoList.propTypes = {
  todos: PropTypes.arrayOf(PropTypes.object).isRequired,
  onToggle: PropTypes.func.isRequired
}

export default TodoList
