// vue-crash-course/src/App.vue
<template>
  <div id="app">
    <h1>Todo application</h1>
    <AddTodo
      @add-todo="addTodo"
    />
    <hr>
    <TodoList v-bind:todos="todos"
              @remove-todo="removeTodo"/>
  </div>
</template>

<script>
  import TodoList from '@/components/TodoList'
  import AddTodo from '@/components/AddTodo'

  export default {
    name: 'app',
    data() {
      return {
        todos: [
          // {id: 1, title: 'Купить хлеб', completed: false},
          // {id: 2, title: 'Купить масло', completed: false},
          // {id: 3, title: 'Купить молоко', completed: false}
        ]
      }
    },
    mounted() {
      fetch('https://jsonplaceholder.typicode.com/todos?_limit=5')
        .then(response => response.json())
        .then(json => {
          this.todos = json
        })
    },
    components: {
      TodoList,
      AddTodo
    },
    methods: {
      removeTodo(id) {
        this.todos = this.todos.filter(t => t.id !== id)
      },
      addTodo(todo) {
        this.todos.push(todo)
      }
    }
  }
</script>

<style>
  #app {
    font-family: 'Avenir', Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-align: center;
    color: #2c3e50;
    margin-top: 60px;
  }
</style>

// react-youtube/src/App.js
import React, { useEffect } from 'react';
import TodoList from "./Todo/TodoList";
import Context from "./context";
import AddTodo from "./Todo/AddTodo";

function App() {
  const [todos, setTodos] = React.useState([
      // {id: 1, completed: false, title: 'Купить хлеб'},
      // {id: 2, completed: false, title: 'Купить масло'},
      // {id: 3, completed: false, title: 'Купить молоко'}
    ]
  );

  useEffect(() => {
    fetch('https://jsonplaceholder.typicode.com/todos?_limit=5')
      .then(response => response.json())
      .then(todos => {
        setTodos(todos)
    })
  }, []);

  function toggleTodo(id) {
    setTodos(
      todos.map(todo => {
        if (todo.id === id) {
          todo.completed = !todo.completed
        }
        return todo
      })
    )
  }

  function removeTodo(id) {
    setTodos(todos.filter(todo => todo.id !== id))
  }

  function addTodo(title) {
    setTodos(todos.concat([
      {
        title: title,
        id: Date.now(),
        completed: false
      }
    ]))
  }

  return (
    <Context.Provider value={{removeTodo}}>
      <div className='wrapper'>
        <h1>React tutorial</h1>
        <AddTodo onCreate={addTodo}></AddTodo>
        {todos.length ? <TodoList todos={todos} onToggle={toggleTodo}/> : <p> No todos </p>}

      </div>
    </Context.Provider>
  );
}

export default App;
